### ISSUE TITLE
Memory usage syrockets when trying to generate graph for diagrams package

### ISSUE THREAD

**Issue by jhrcek** [jmillikin/cabal-graphdeps#1]
When generating dependency graph for diagrams package, memory usage is +- constant until the package [old-time-1.1.0.1] is reached.Then the memory usage skyrockets and the program never terminates (I have 8g of memory).

Here's the command I used & its output: 

$ cabal-graphdeps diagrams | tred | dot -Tpng > ~/diagrams-dependencies.png
[diagrams]
[JuicyPixels-3.2.6.1]
[array-0.5.1.0]
[binary-0.7.6.1]
[bytestring-0.10.6.0]
[deepseq-1.4.1.2]
[containers-0.5.6.3]
[mtl-2.2.1]
[transformers-0.4.3.0]
[primitive-0.6]
[vector-0.11.0.0]
[zlib-0.6.1.1]
[MonadRandom-0.4]
[random-1.1]
[time-1.5.0.1]
[transformers-compat-0.4.0.4]
[StateVar-1.1.0.1]
[stm-2.4.4]
[active-0.2.0.5]
[adjunctions-4.2.2]
[base-orphans-0.4.4]
[bifunctors-5]
[hashable-1.2.3.3]
[text-1.2.1.3]
[nats-1]
[pretty-1.1.3.2]
[semigroups-0.17.0.1]
[tagged-0.8.1]
[template-haskell-2.8.0.0]
[unordered-containers-0.2.5.1]
[comonad-4.2.7.2]
[contravariant-1.3.3]
[void-0.7.1]
[distributive-0.4.4]
[exceptions-0.8.0.2]
[free-4.12.1]
[prelude-extras-0.4.0.2]
[profunctors-5.1.1]
[semigroupoids-5.0.0.4]
[bytes-0.15.0.1]
[cereal-0.4.1.1]
[filepath-1.4.0.0]
[kan-extensions-4.2.3]
[lens-4.13]
[parallel-3.2.0.6]
[reflection-2.1]
[linear-1.20.1]
[ansi-terminal-0.6.2.3]
[unix-2.7.1.0]
[ansi-wl-pprint-0.6.7.3]
[async-2.0.2]
[base64-bytestring-1.0.0.1]
[blaze-builder-0.4.0.1]
[bytestring-builder-0.10.6.0.0]
[circle-packing-0.1.0.4]
[colour-2.3.3]
[data-default-0.5.3]
[data-default-class-0.0.1]
[data-default-instances-base-0.0.1]
[data-default-instances-containers-0.0.1]
[data-default-instances-dlist-0.0.1]
[dlist-0.7.1.2]
[data-default-instances-old-locale-0.0.1]
[old-locale-1.0.0.7]
[diagrams-1.3]
[diagrams-contrib-1.3.0.5]
[diagrams-core-1.3.0.3]
[dual-tree-0.2.0.7]
[groups-0.4.0.0]
[monoid-extras-0.4.0.2]
[newtype-0.2]
[diagrams-lib-1.3.0.3]
[diagrams-solve-0.1]
[directory-1.2.3.1]
[fingertree-0.1.1.0]
[fsnotify-0.2.1]
[hinotify-0.3.8.1]
[unix-compat-0.4.1.4]
[intervals-0.7.1]
[lens-4.12.3]
[reflection-2]
[linear-1.19.1.3]
[optparse-applicative-0.11.0.2]
[process-1.2.3.0]
[semigroups-0.16.2.2]
[force-layout-0.4.0.2]
[parsec-3.1.9]
[split-0.2.2]
[diagrams-svg-1.3.1.4]
[lucid-2.9.2]
[lucid-svg-0.5.0.0]
[old-time-1.1.0.1]                                    <- up until now the memory usage is constant, but then ...
^C                                                           <------------- Have to kill it here, because it starts trashing

**Comment by jmillikin** [comment]
I've uploaded version 0.1.3, which uses smarter pruning when rendering graphs (commit a3b47ddceb245205219c419614105641fdb396f5). It's able to render the graph for "diagrams" with no issues.

**Comment by jhrcek** [comment]
Tested the new version and now it works. Thanks for the fix!
